DROP All OBJECTS;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS users
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(255),
    email varchar(512) UNIQUE
    );

CREATE TABLE IF NOT EXISTS items
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255),
    description  varchar(512),
    is_available boolean,
    owner_id     int,
    request_id   int,
    constraint fk_items_to_users FOREIGN KEY (owner_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS booking
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP,
    end_time   TIMESTAMP,
    item_id    INT NOT NULL,
    booker_id  INT,
    status     VARCHAR(100),
    constraint fk_booking_items FOREIGN KEY (item_id) references items (id),
    constraint fk_booking_users FOREIGN KEY (booker_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS comments
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      varchar(512),
    item_id   INT,
    author_id INT,
    created   TIMESTAMP,
    constraint fk_comments_items FOREIGN KEY (item_id) references items(id),
    constraint fk_comments_users FOREIGN KEY (author_id) references users(id)
    );
CREATE TABLE IF NOT EXISTS requests
(
    request_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(512),
    requestor_id INT,
    date_created TIMESTAMP,
    constraint fk_requests_users FOREIGN KEY (requestor_id) references users (id)
    );